<div class="menu">

    <div class="menu__column">
        <h4><?php echo __('HELP')?></h4>
        <ul>
            <li><a href="#"><?php echo __('Shipping & Returns')?></a></li>
            <li><a href="#"><?php echo __('Track Your Order')?></a></li>
            <li><a href="#"><?php echo __('Store Finder')?></a></li>
            <li><a href="#"><?php echo __('FAQs')?></a></li>
        </ul>
    </div>
    
    <div class="menu__column">
        <h4><?php echo __('ABOUT')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('About Us')?>"><?php echo __('About Us')?></a></li>
            <li><a href="#" title="<?php echo __('Contact Us')?>"><?php echo __('Contact Us')?></a></li>
            <li><a href="#" title="<?php echo __('Careers')?>"><?php echo __('Careers')?></a></li>
            <li><a href="#" title="<?php echo __('Become an Affiliate')?>"><?php echo __('Become an Affiliate')?></a></li>

        </ul>
    </div>

    <div class="menu__column">
        <h4><?php echo __('CATEGORIES')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('Shirts')?>"><?php echo __('Shirts')?></a></li>
            <li><a href="#" title="<?php echo __('Jeans')?>"><?php echo __('Jeans')?></a></li>
            <li><a href="#" title="<?php echo __('Footwear')?>"><?php echo __('Footwear')?></a></li>
            <li><a href="#" title="<?php echo __('Accessories')?>"><?php echo __('Accessories')?></a></li>
        </ul>
    </div>

    <div class="menu__column">
        <h4><?php echo __('JOIN THE LIST AND RECEIVE 15% OFF YOUR FIRST ORDER')?></h4>
        <ul>
            <li>
                <form>
                    <input type="email" id="enter" name="email" placeholder="Your Email">
                    <button type="submit" id="send">SEND</button>
                </form>
            </li>
        </ul>
    </div>

</div>